name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            echo "🚀 Starting Deployment..."
            cd /var/www/Codigix-Task-CRM
            
            # Fetch latest changes
            git pull origin main

            # Build & Reload Client
            echo "🎨 Deploying client..."
            cd /var/www/Codigix-Task-CRM/client
            npm install
            GENERATE_SOURCEMAP=false DISABLE_ESLINT_PLUGIN=true npm run build

            # Update & Restart Server
            echo "📦 Deploying Backend..."
            cd /var/www/Codigix-Task-CRM/server
            npm install --production
            echo "🗄️ Running Prisma Migrations..."
            npx prisma generate
            node prisma/auto-migrate.js
            pm2 restart Codigix-Task-CRM-backend 


            # Save PM2 state
            pm2 save
            echo "✅ Deployment Complete!"
